name: master_detail_scaffold
description: A package for implementing a responsive master-detail scaffold widget
version: 1.1.1
homepage: https://github.com/MaikuB/master_detail_scaffold

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: